name: Flujo uno
on: workflow_dispatch
jobs:
  dependenciasjob:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener c√≥digo
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20 

      - name: Instalar Dependencias
        run: npm ci

      - name: lint
        run: npm run lint

  testjob:
    needs: dependenciasjob
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: npm test


  buildjob:      
    needs: testjob 
    runs-on: ubuntu-latets
    
    steps:
      - name: build
        run: npm run build

  desplegarjob:
    needs: buildjob
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue
        run: echo "Se ha realizado el despliegue"
