name: Flujo uno
on: workflow_dispatch
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:

      - name: Obtener c√≥digo
        uses: actions/checkout@v4

      - name: Instalar NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20 

      - name: Instalar Dependencias
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm tests

      - name: build
        run: npm run build

  desplegar:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue
        run: echo "Se ha realizado el despliegue"
 
    